services:
  ch1:
    image: clickhouse/clickhouse-server:latest-alpine
    restart: on-failure:10
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro1.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./keeper1.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ch1data:/var/lib/clickhouse
    ports:
      - '8123:8123'
      - '9001:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
  ch2:
    image: clickhouse/clickhouse-server:latest-alpine
    restart: on-failure:10
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro2.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./keeper2.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ch2data:/var/lib/clickhouse
    ports:
      - '8124:8123'
      - '9002:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
    depends_on:
      ch1:
        condition: service_started
  ch3:
    image: clickhouse/clickhouse-server:latest-alpine
    restart: on-failure:10
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.d/local.xml
      - ./macro3.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./keeper3.xml:/etc/clickhouse-server/config.d/keeper.xml
      - ch3data:/var/lib/clickhouse
    ports:
      - '8125:8123'
      - '9003:9000'
    ulimits:
      nproc: 65536
      nofile:
        soft: 252144
        hard: 252144
    depends_on:
      ch1:
        condition: service_started

volumes:
  ch1data:
  ch2data:
  ch3data:
