version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"  # web ui
      - "7687:7687"  # db
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_security_auth__enabled=true
      - NEO4J_dbms_connector_bolt_tls__level=DISABLED
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"  # HTTP-интерфейс для запросов
      - "9000:9000"  # TCP-интерфейс для запросов
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
