version: '3.7'

services:
  # MongoDB Cluster
  mongo1:
    image: mongo
    container_name: mongo1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --replSet rs0 --bind_ip_all
    ports:
      - '27017:27017'
    networks:
      - mongo-cluster

  mongo2:
    image: mongo
    container_name: mongo2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster

  mongo3:
    image: mongo
    container_name: mongo3
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    command: --replSet rs0 --bind_ip_all
    networks:
      - mongo-cluster

  # Neo4j Cluster
  neo4j1:
    image: neo4j:latest
    container_name: neo4j1
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_mode=CORE
      - NEO4J_dbms_connector_bolt_tls__level=DISABLED
      - NEO4J_dbms_default__advertised__address=neo4j1
      - NEO4J_dbms_default__listen__address=0.0.0.0
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - neo4j-cluster

  neo4j2:
    image: neo4j:latest
    container_name: neo4j2
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_mode=CORE
      - NEO4J_dbms_connector_bolt_tls__level=DISABLED
      - NEO4J_dbms_default__advertised__address=neo4j2
      - NEO4J_dbms_default__listen__address=0.0.0.0
    networks:
      - neo4j-cluster

  neo4j3:
    image: neo4j:latest
    container_name: neo4j3
    environment:
      - NEO4J_AUTH=neo4j/password123
      - NEO4J_dbms_mode=CORE
      - NEO4J_dbms_connector_bolt_tls__level=DISABLED
      - NEO4J_dbms_default__advertised__address=neo4j3
      - NEO4J_dbms_default__listen__address=0.0.0.0
    networks:
      - neo4j-cluster

  # ClickHouse Cluster with Zookeeper
  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - clickhouse-cluster

  clickhouse1:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse1
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    depends_on:
      - zookeeper
    ports:
      - "8123:8123"
      - "9000:9000"
    networks:
      - clickhouse-cluster

  clickhouse2:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse2
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    depends_on:
      - zookeeper
    networks:
      - clickhouse-cluster

  clickhouse3:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse3
    environment:
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
    depends_on:
      - zookeeper
    networks:
      - clickhouse-cluster

networks:
  mongo-cluster:
    driver: bridge
  neo4j-cluster:
    driver: bridge
  clickhouse-cluster:
    driver: bridge