app:
  name: 'basket'
  version: '1.0.0'

http:
  port: '8080'

mongo:
  mongo_url: "mongodb://mongo:mongo@localhost:27017/"
  mongo_db: "players"

logger:
  log_level: 'debug'
  rollbar_env: 'basket'
