app:
  name: "basket"
  version: "1.0.0"

http:
  port: "8080"

mongo:
  mongo_url: "mongodb://127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/?replicaSet=rs0"
  mongo_db: "basket"

neo4j:
  neo4j_url: "neo4j://127.0.0.1:7687"
  neo4j_login: "neo4j"
  neo4j_password: "neo4j"

logger:
  log_level: "debug"
  rollbar_env: "basket"

clickhouse:
  clickhouse_url: "clickhouse://localhost:9001,localhost:9002,localhost:9003/default?debug=true"

