app:
  name: "basket"
  version: "1.0.0"

http:
  port: "8080"

mongo:
  mongo_url: "mongodb://mongo:mongo@localhost:27017/"
  mongo_db: "basket"

neo4j:
  neo4j_url: "bolt://localhost:7687"
  neo4j_login: "neo4j"
  neo4j_password: "password123"

logger:
  log_level: "debug"
  rollbar_env: "basket"
