// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/award": {
            "post": {
                "description": "Create new award",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "award"
                ],
                "summary": "Create award",
                "operationId": "create-award",
                "parameters": [
                    {
                        "description": "Enter new award info",
                        "name": "award",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Award"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.createAwardResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/award/list": {
            "get": {
                "description": "Get award list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "award"
                ],
                "summary": "Get award list",
                "operationId": "get-award-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Enter page number",
                        "name": "page_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Award"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/award/{id}": {
            "get": {
                "description": "Get award by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "award"
                ],
                "summary": "Get award",
                "operationId": "get-award",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter award id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Award"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update award by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "award"
                ],
                "summary": "Update award",
                "operationId": "update-award",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id award",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enter new award info for update",
                        "name": "award",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Award"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Award"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete award by id",
                "tags": [
                    "award"
                ],
                "summary": "Delete award",
                "operationId": "delete-award",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id award",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/game": {
            "post": {
                "description": "Create new game",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Create game",
                "operationId": "create-game",
                "parameters": [
                    {
                        "description": "Enter new game info",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Game"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.createGameResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/game/list": {
            "get": {
                "description": "Get game list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get game list",
                "operationId": "get-game-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Enter page number",
                        "name": "page_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/game/{id}": {
            "get": {
                "description": "Get game by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Get game",
                "operationId": "get-game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter game id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update game by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "game"
                ],
                "summary": "Update game",
                "operationId": "update-game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id game",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enter new game info for update",
                        "name": "game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Game"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Game"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete game by id",
                "tags": [
                    "game"
                ],
                "summary": "Delete game",
                "operationId": "delete-game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id game",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/league": {
            "post": {
                "description": "Create new league",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Create league",
                "operationId": "create-league",
                "parameters": [
                    {
                        "description": "Enter new league info",
                        "name": "league",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.League"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.createLeagueResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/league/list": {
            "get": {
                "description": "Get league list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get league list",
                "operationId": "get-league-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Enter page number",
                        "name": "page_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.League"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/league/{id}": {
            "get": {
                "description": "Get league by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Get league",
                "operationId": "get-league",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter league id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.League"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update league by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "league"
                ],
                "summary": "Update league",
                "operationId": "update-league",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id league",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enter new league info for update",
                        "name": "league",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.League"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.League"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete league by id",
                "tags": [
                    "league"
                ],
                "summary": "Delete league",
                "operationId": "delete-league",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id league",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/player": {
            "post": {
                "description": "Create new player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "Create player",
                "operationId": "create-player",
                "parameters": [
                    {
                        "description": "Enter new player info",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/v1.createPlayerResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/player/list": {
            "get": {
                "description": "Get player list",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "Get player list",
                "operationId": "get-player-list",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Enter page number",
                        "name": "page_number",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/player/{id}": {
            "get": {
                "description": "Get player by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "Get player",
                "operationId": "get-player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter player id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update player by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "player"
                ],
                "summary": "Update player",
                "operationId": "update-player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id player",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Enter new player info for update",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.Player"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete player by id",
                "tags": [
                    "player"
                ],
                "summary": "Delete player",
                "operationId": "delete-player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter id player",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/stat_awards": {
            "post": {
                "description": "Create new record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "record"
                ],
                "summary": "Create record",
                "operationId": "create-record",
                "parameters": [
                    {
                        "description": "Enter new record info",
                        "name": "player",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entity.RewardStat"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/stat_awards/match/{id}": {
            "get": {
                "description": "Get stat by match id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stat"
                ],
                "summary": "Get stat by match",
                "operationId": "get-stat-match",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter match id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.RewardStat"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/stat_awards/player/{id}": {
            "get": {
                "description": "Get stat by player id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stat"
                ],
                "summary": "Get stat by player",
                "operationId": "get-stat-player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter player id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.RewardStat"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/stat_awards/reward/{id}": {
            "get": {
                "description": "Get stat by reward id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stat"
                ],
                "summary": "Get stat by reward",
                "operationId": "get-stat-reward",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter reward id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.RewardStat"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        },
        "/stat_awards/tournament/{id}": {
            "get": {
                "description": "Get stat by tournament id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stat"
                ],
                "summary": "Get stat by tournament",
                "operationId": "get-stat-tournament",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Enter tournament id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.RewardStat"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/v1.errResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Award": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "default": "MVP of season 2024"
                },
                "surname": {
                    "type": "string",
                    "default": "Best player of season 2024"
                }
            }
        },
        "entity.Game": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string",
                    "default": "12.03.24"
                },
                "first_team": {
                    "type": "string",
                    "default": "LA Lakers"
                },
                "league": {
                    "type": "string",
                    "default": "NBA"
                },
                "second_team": {
                    "type": "string",
                    "default": "Chicago Bulls"
                },
                "type": {
                    "type": "string",
                    "default": "final"
                }
            }
        },
        "entity.League": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "default": "NBA"
                },
                "season": {
                    "type": "string",
                    "default": "2023/2024"
                }
            }
        },
        "entity.Player": {
            "type": "object",
            "properties": {
                "age": {
                    "type": "integer",
                    "default": 34
                },
                "citizenship": {
                    "type": "string",
                    "default": "USA"
                },
                "height": {
                    "type": "integer",
                    "default": 201
                },
                "middle_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "default": "Jimmi"
                },
                "role": {
                    "type": "string",
                    "default": "heavy forward"
                },
                "surname": {
                    "type": "string",
                    "default": "Butler"
                },
                "team": {
                    "type": "string",
                    "default": "Miami Heat"
                },
                "weight": {
                    "type": "integer",
                    "default": 104
                }
            }
        },
        "entity.RewardStat": {
            "type": "object",
            "properties": {
                "match": {
                    "type": "string"
                },
                "player": {
                    "type": "string"
                },
                "reward": {
                    "type": "string"
                },
                "tournament": {
                    "type": "string"
                }
            }
        },
        "v1.createAwardResp": {
            "type": "object",
            "properties": {
                "award_id": {
                    "type": "string"
                }
            }
        },
        "v1.createGameResp": {
            "type": "object",
            "properties": {
                "game_id": {
                    "type": "string"
                }
            }
        },
        "v1.createLeagueResp": {
            "type": "object",
            "properties": {
                "league_id": {
                    "type": "string"
                }
            }
        },
        "v1.createPlayerResp": {
            "type": "object",
            "properties": {
                "playerID": {
                    "type": "string"
                }
            }
        },
        "v1.errResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{"http"},
	Title:            "Basket LAB",
	Description:      "Basket no-sql lab",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
